services:
  postgres:
    image: postgres:16
    container_name: tb81tube-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tb81tube
    ports:
      - "5432:5432"
    volumes:
      - tb81tube-postgres-data:/var/lib/postgresql/data

volumes:
  tb81tube-postgres-data:
